### PR TITLE
Skip over "popup" types when selecting next window.

### PR DESCRIPTION
**Pull request by heisencoder**
See Issue #10

### CODE REVIEW

**Comment by heisencoder** [comment]
Let me know if you'd also like the minor rev bumped in the version number.

**Comment by heisencoder** [comment]
Is this repo still maintained?

**Comment by luyangkenneth** [comment]
Hey sorry I don't have time to work on this right now!

**Comment by heisencoder** [comment]
No problem!  I've cloned this repo and am adding new features here:  https://github.com/heisencoder/tab-shortcuts

**Pull request closed without merging**
